"""empty message

Revision ID: 26704d1d6dd1
Revises: 
Create Date: 2022-07-01 16:25:35.991748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26704d1d6dd1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_whitelist',
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.PrimaryKeyConstraint('email_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('player',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('player_name', sa.String(length=80), nullable=True),
    sa.Column('pin_confirmation_url_part', sa.String(length=24), nullable=True),
    sa.Column('pin_code_hash', sa.String(length=200), nullable=True),
    sa.Column('pin_code_timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('player_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('game',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('game_created_by', sa.Integer(), nullable=False),
    sa.Column('game_created_timestamp', sa.DateTime(), nullable=False),
    sa.Column('team_1_won', sa.Boolean(), nullable=True),
    sa.Column('win_result_submitted_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_created_by'], ['player.player_id'], ),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_table('players_in_game',
    sa.Column('games_and_players_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.game_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.player_id'], ),
    sa.PrimaryKeyConstraint('games_and_players_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players_in_game')
    op.drop_table('game')
    op.drop_table('player')
    op.drop_table('email_whitelist')
    # ### end Alembic commands ###
